/**
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Alert
import io.swagger.client.models.V2RegionType

/**
 * 
 * @param regionId 
 * @param regionType 
 * @param regionName 
 * @param regionEngName 
 * @param lastUpdate 
 * @param activeAlerts 
 */
data class AlertRegionModel (

    val regionId: kotlin.String? = null,
    val regionType: V2RegionType? = null,
    val regionName: kotlin.String? = null,
    val regionEngName: kotlin.String? = null,
    val lastUpdate: java.time.LocalDateTime? = null,
    val activeAlerts: kotlin.Array<Alert>? = null
) {
}