/**
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * Values: UNKNOWN,AIR,ARTILLERY,URBANFIGHTS,CHEMICAL,NUCLEAR,INFO
 */
enum class AlertType(val value: kotlin.String){
    UNKNOWN("UNKNOWN"),// :/
    AIR("AIR"),// :/
    ARTILLERY("ARTILLERY"),// :/
    URBANFIGHTS("URBAN_FIGHTS"),// :/
    CHEMICAL("CHEMICAL"),// :/
    NUCLEAR("NUCLEAR"),// :/
    INFO("INFO");// :/
}