/**
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AlertType
import io.swagger.client.models.TimeSpan

/**
 * 
 * @param regionId 
 * @param startDate 
 * @param endDate 
 * @param duration 
 * @param alertType 
 * @param regionName 
 * @param isContinue 
 */
data class RegionAlarmModel (

    val regionId: kotlin.String? = null,
    val startDate: java.time.LocalDateTime? = null,
    val endDate: java.time.LocalDateTime? = null,
    val duration: TimeSpan? = null,
    val alertType: AlertType? = null,
    val regionName: kotlin.String? = null,
    val isContinue: kotlin.Boolean? = null
) {
}