/**
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RegionAlarmModel

/**
 * 
 * @param regionId 
 * @param regionName 
 * @param alarms 
 */
data class RegionAlarmsHistory (

    val regionId: kotlin.String? = null,
    val regionName: kotlin.String? = null,
    val alarms: kotlin.Array<RegionAlarmModel>? = null
) {
}